apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_dpdk_a",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["10ed"],
                    "drivers": ["igb_uio"],
                    "pfNames": ["ens785f0"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk_b",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["10ed"],
                    "drivers": ["igb_uio"],
                    "pfNames": ["ens785f1"]
                }
            }

        ]
    }

